import burger from "./files/burger.js";
import changeNumber from "./files/change-number.js";
import headerScroll from "./files/headaer-scroll.js";
import maps from "./files/maps.js";
import modal from "./files/modal.js";
import sliders from "./files/sliders.js";
import smoothScroll from "./files/smooth-scroll.js";
import spoller from "./files/spoller.js";
import switchPages from "./files/switch-pages.js";
import tab from "./files/tab.js";
import videos from "./files/videos.js";

burger();
switchPages();
headerScroll();
sliders();
tab();
maps();
videos();
smoothScroll();
changeNumber();
modal();
spoller();